      SUBROUTINE HYEDIT (IEDFLG,FILE)
C--RUN AN EDITOR WITHIN HYPOINVERSE. USED TO INTERACTIVELY PROCESS EVENTS.
C--PORT LINUX/GFORTRAN: no-op. Solo se usaba en el flujo interactivo VMS.
      INTEGER IEDFLG
      CHARACTER FILE*(*)
      RETURN
      END
