      SUBROUTINE HYTIME (CURTIM)
C--RETURNS THE CURRENT TIME AND DATE AS A 28 CHARACTER STRING
C--PORT LINUX/GFORTRAN: se usa DATE_AND_TIME en lugar de DATE/TIME (VMS).
      CHARACTER CURTIM*28
      CHARACTER DAT*8, TIM*10
      CALL DATE_AND_TIME (DAT, TIM)
      CURTIM = DAT(1:4)//'/'//DAT(5:6)//'/'//DAT(7:8)//' '//
     &         TIM(1:2)//':'//TIM(3:4)//':'//TIM(5:6)//'   '
      RETURN
      END
